version: '3.7'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server

    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./src/db:/var/lib/src
      - ./src/logs:/var/log/src-server
    ulimits:
      nofile: 262144
    networks:
      - my_net

  backend:
    build: .
    ports:
      - '9090:9090'
    depends_on:
      clickhouse-server:
        condition: service_started
    container_name: backend
    networks:
      - my_net

networks:
  my_net:
    name: my_net
