version: '3'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server

    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./clickhouse/db:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
    ulimits:
      nofile: 262144
